# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3659c39e592ec0fa41112f04c4db27519e65c6598f4a040a97a0b484e592d1442ed544d90a6f828e25c1be86266c8cfac85f213711063772f5e2b394d9b8b2cc

test:
  secret_key_base: fb188b13ce299444d25f0e097a353dd8a81cef6e634d9ae8ce0d2362c9acc07975968186db404de6cd01312d2e60e6761f4d0b2392fac28b49b199ceed277a64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
